version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    
    image: eventshuffle:latest

    command: python manage.py runserver 0.0.0.0:8080

    ports: 
      - '8080:8080'

    container_name: eventshuffle_container